[package]
name = "drawbridge"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[workspace]

[dependencies]
# Internal dependencies
drawbridge-auth = { path = "./crates/auth" }
drawbridge-http = { path = "./crates/http" }
drawbridge-tags = { path = "./crates/tags" }
drawbridge-tree = { path = "./crates/tree" }

# External dependencies
async-h1 = "2.3.3"
async-std = "1.11.0"
