[package]
name = "drawbridge"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[workspace]

[dependencies]
# Internal dependencies
drawbridge-auth = { path = "./crates/auth" }
drawbridge-tags = { path = "./crates/tags" }
drawbridge-tree = { path = "./crates/tree" }

# External dependencies
axum = "0.4.8"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
