[package]
name = "drawbridge-tree"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
base64 = "0.13.0"
drawbridge-core = { path = "../core" }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha2 = "0.10.2"
tempfile = "3.3.0"
